# Generated by Django 6.0.3 on 2026-05-03 16:36

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0003_alter_integrationconnection_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integrationconnection",
            name="external_account_id",
            field=core.fields.TruncatingCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="integrationconnection",
            name="external_account_name",
            field=core.fields.TruncatingCharField(
                blank=True, default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="integrationconnection",
            name="provider",
            field=core.fields.TruncatingCharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="integrationconnection",
            name="provider_category",
            field=core.fields.TruncatingCharField(
                choices=[
                    ("social_media", "Social Media"),
                    ("marketing", "Marketing"),
                    ("ecommerce", "E-Commerce"),
                    ("storage", "Storage"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="integrationconnection",
            name="status",
            field=core.fields.TruncatingCharField(
                choices=[
                    ("active", "Active"),
                    ("expired", "Expired"),
                    ("revoked", "Revoked"),
                    ("error", "Error"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
