# Generated by Django 5.2 on 2026-03-26 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_library", "0004_add_type_to_imagegroup"),
        ("social_media", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialmediapost",
            name="ai_instruction",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="socialmediapost",
            name="post_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("product", "Product"),
                    ("lifestyle", "Lifestyle"),
                    ("ad", "Ad"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="socialmediapost",
            name="topic",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.CreateModel(
            name="SocialMediaPostSeedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="media_library.image",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seed_images",
                        to="social_media.socialmediapost",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
    ]
