# Generated by Django 5.2.13 on 2026-04-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0007_delete_socialmediasettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialmediapostplatform",
            name="publish_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="socialmediapostplatform",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
