# Generated by Django 6.0.3 on 2026-04-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0008_add_platform_publish_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialmediapostplatform",
            name="published_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="socialmediapost",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("scheduled", "Scheduled"),
                    ("publishing", "Publishing"),
                    ("published", "Published"),
                    ("failed", "Failed"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
