# Generated by Django 6.0.3 on 2026-05-03 16:36

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0011_rename_image_to_media"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialmediapost",
            name="post_type",
            field=core.fields.TruncatingCharField(
                blank=True,
                choices=[
                    ("product", "Product"),
                    ("lifestyle", "Lifestyle"),
                    ("ad", "Ad"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="socialmediapost",
            name="status",
            field=core.fields.TruncatingCharField(
                choices=[
                    ("draft", "Draft"),
                    ("scheduled", "Scheduled"),
                    ("publishing", "Publishing"),
                    ("published", "Published"),
                    ("failed", "Failed"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="socialmediapost",
            name="title",
            field=core.fields.TruncatingCharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="socialmediapost",
            name="topic",
            field=core.fields.TruncatingCharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="socialmediapostplatform",
            name="platform",
            field=core.fields.TruncatingCharField(
                choices=[
                    ("linkedin", "LinkedIn"),
                    ("x", "X (Twitter)"),
                    ("facebook", "Facebook"),
                    ("instagram", "Instagram"),
                ],
                max_length=20,
            ),
        ),
    ]
