# Generated by Django 6.0.3 on 2026-05-03 17:26

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0013_alter_socialmediapost_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialmediapost",
            name="processing_status",
            field=core.fields.TruncatingCharField(
                choices=[
                    ("idle", "Idle"),
                    ("generating", "Generating"),
                    ("completed", "Completed"),
                    ("error", "Error"),
                ],
                default="idle",
                max_length=20,
            ),
        ),
    ]
