# Generated by Django 5.2 on 2026-03-25 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brand", "0001_initial"),
        ("media_library", "0004_add_type_to_imagegroup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="logo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="logo_brands",
                to="media_library.imagegroup",
            ),
        ),
    ]
