# Generated by Django 6.0.3 on 2026-04-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brand", "0006_add_brand_tone_audience_fonts_colors"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("idle", "Idle"),
                    ("scraping", "Scraping"),
                    ("error", "Error"),
                ],
                default="idle",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="scrape_error",
            field=models.TextField(blank=True),
        ),
    ]
