# Generated by Django 6.0.3 on 2026-05-03 16:36

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("brand", "0008_alter_brand_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="language",
            field=core.fields.TruncatingCharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=core.fields.TruncatingCharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="brand",
            name="primary_color",
            field=core.fields.TruncatingCharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name="brand",
            name="processing_status",
            field=core.fields.TruncatingCharField(
                choices=[
                    ("idle", "Idle"),
                    ("scraping", "Scraping"),
                    ("error", "Error"),
                ],
                default="idle",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="secondary_color",
            field=core.fields.TruncatingCharField(blank=True, max_length=7),
        ),
    ]
