# Generated by Django 6.0.3 on 2026-04-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_project_platform_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="product_import_in_progress",
            field=models.BooleanField(default=False),
        ),
    ]
