# Generated by Django 6.0.3 on 2026-05-13 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_alter_project_language_alter_project_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="default_publish_time",
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
