# Generated by Django 6.0.3 on 2026-05-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_add_default_publish_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="timezone",
            field=models.CharField(default="UTC", max_length=64),
        ),
    ]
