# Generated by Django 6.0.3 on 2026-05-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_add_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="enable_autopost",
            field=models.BooleanField(default=True),
        ),
    ]
