# Generated by Django 6.0.3 on 2026-05-03 16:36

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customuser_stripe_customer_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="company_name",
            field=core.fields.TruncatingCharField(
                blank=True, default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="stripe_customer_id",
            field=core.fields.TruncatingCharField(
                blank=True, default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="stripe_subscription_id",
            field=core.fields.TruncatingCharField(
                blank=True, default="", max_length=255
            ),
        ),
    ]
