# Generated by Django 6.0.3 on 2026-05-05 05:48

import core.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_customuser_company_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    core.fields.TruncatingCharField(
                        blank=True, default="", max_length=255
                    ),
                ),
                (
                    "vat_id",
                    core.fields.TruncatingCharField(
                        blank=True, default="", max_length=64, verbose_name="VAT ID"
                    ),
                ),
                (
                    "address_line_1",
                    core.fields.TruncatingCharField(
                        blank=True, default="", max_length=255
                    ),
                ),
                (
                    "address_line_2",
                    core.fields.TruncatingCharField(
                        blank=True, default="", max_length=255
                    ),
                ),
                (
                    "city",
                    core.fields.TruncatingCharField(
                        blank=True, default="", max_length=100
                    ),
                ),
                (
                    "state",
                    core.fields.TruncatingCharField(
                        blank=True, default="", max_length=100
                    ),
                ),
                (
                    "zip_code",
                    core.fields.TruncatingCharField(
                        blank=True, default="", max_length=20
                    ),
                ),
                (
                    "country",
                    core.fields.TruncatingCharField(
                        blank=True,
                        default="",
                        help_text="ISO 3166-1 alpha-2 country code",
                        max_length=2,
                    ),
                ),
                (
                    "phone",
                    core.fields.TruncatingCharField(
                        blank=True, default="", max_length=32
                    ),
                ),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("website", models.URLField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "companies",
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="accounts.company",
            ),
        ),
    ]
