# Generated by Django 6.0.3 on 2026-05-05 05:48

import uuid

from django.db import migrations


def create_companies_for_existing_users(apps, schema_editor):
    CustomUser = apps.get_model('accounts', 'CustomUser')
    Company = apps.get_model('accounts', 'Company')
    users_without_company = CustomUser.objects.filter(company__isnull=True)
    for user in users_without_company:
        company = Company.objects.create(
            id=uuid.uuid4(),
            name=user.company_name or '',
        )
        user.company = company
        user.save(update_fields=['company'])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_company_model"),
    ]

    operations = [
        migrations.RunPython(
            create_companies_for_existing_users,
            migrations.RunPython.noop,
        ),
    ]
