# Generated by Django 6.0.3 on 2026-05-05 06:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_backfill_user_companies"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                -- 1. Add uuid column, copy existing UUID id values into it
                ALTER TABLE accounts_company ADD COLUMN uuid uuid;
                UPDATE accounts_company SET uuid = id::uuid;

                -- 2. Temporarily store company UUID → new int mapping via a sequence
                CREATE SEQUENCE accounts_company_id_seq AS bigint;
                ALTER TABLE accounts_company ADD COLUMN new_id bigint DEFAULT nextval('accounts_company_id_seq');
                ALTER SEQUENCE accounts_company_id_seq OWNED BY accounts_company.new_id;

                -- 3. Drop FK from customuser (company_id was UUID referencing old id)
                DO $$
                DECLARE r record;
                BEGIN
                    FOR r IN
                        SELECT tc.constraint_name
                        FROM information_schema.table_constraints tc
                        JOIN information_schema.key_column_usage kcu
                            ON tc.constraint_name = kcu.constraint_name
                            AND tc.table_schema = kcu.table_schema
                        WHERE tc.table_name = 'accounts_customuser'
                            AND kcu.column_name = 'company_id'
                            AND tc.constraint_type = 'FOREIGN KEY'
                    LOOP
                        EXECUTE 'ALTER TABLE accounts_customuser DROP CONSTRAINT ' || r.constraint_name;
                    END LOOP;
                END $$;

                -- 4. Add new bigint company_id column on customuser and populate from mapping
                ALTER TABLE accounts_customuser ADD COLUMN company_id_new bigint;
                UPDATE accounts_customuser cu
                SET company_id_new = c.new_id
                FROM accounts_company c
                WHERE cu.company_id::uuid = c.uuid;

                -- 5. Drop old UUID company_id from customuser
                ALTER TABLE accounts_customuser DROP COLUMN company_id;
                ALTER TABLE accounts_customuser RENAME COLUMN company_id_new TO company_id;

                -- 6. Replace company PK: drop UUID id, promote new_id to id
                ALTER TABLE accounts_company DROP CONSTRAINT accounts_company_pkey;
                ALTER TABLE accounts_company DROP COLUMN id;
                ALTER TABLE accounts_company RENAME COLUMN new_id TO id;
                ALTER TABLE accounts_company ADD PRIMARY KEY (id);

                -- 7. Make uuid not-null and unique
                ALTER TABLE accounts_company ALTER COLUMN uuid SET NOT NULL;
                ALTER TABLE accounts_company ADD CONSTRAINT accounts_company_uuid_key UNIQUE (uuid);

                -- 8. Recreate FK from customuser.company_id → accounts_company.id
                ALTER TABLE accounts_customuser
                    ADD CONSTRAINT accounts_customuser_company_id_fk
                    FOREIGN KEY (company_id) REFERENCES accounts_company(id)
                    ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql=migrations.RunSQL.noop,
            state_operations=[
                migrations.AddField(
                    model_name="company",
                    name="uuid",
                    field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                migrations.AlterField(
                    model_name="company",
                    name="id",
                    field=models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
            ],
        ),
    ]
