# Generated by Django 6.0.3 on 2026-03-29 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "media_library",
            "0005_aiimagegeneration_aiimagegenerationattachment_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aiimagegenerationresult",
            name="generation",
        ),
        migrations.RemoveField(
            model_name="aiimagegenerationattachment",
            name="generation",
        ),
        migrations.RemoveField(
            model_name="aiimagegenerationattachment",
            name="source_image",
        ),
        migrations.RemoveField(
            model_name="aiimagegenerationresult",
            name="image",
        ),
        migrations.DeleteModel(
            name="AIImageGeneration",
        ),
        migrations.DeleteModel(
            name="AIImageGenerationAttachment",
        ),
        migrations.DeleteModel(
            name="AIImageGenerationResult",
        ),
    ]
