# Generated by Django 6.0.3 on 2026-03-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_library", "0006_remove_aiimagegenerationresult_generation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="image_type",
            field=models.CharField(
                choices=[("manual", "Manual"), ("generated", "Generated")],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="imagegroup",
            name="type",
            field=models.CharField(
                choices=[
                    ("product", "Product"),
                    ("manual", "Manual"),
                    ("generated", "Generated"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
    ]
