# Generated by Django 6.0.3 on 2026-05-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_library", "0009_alter_imagegroup_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagegroup",
            name="source_url",
            field=models.URLField(blank=True),
        ),
    ]
