# Generated by Django 6.0.3 on 2026-05-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_library", "0010_add_source_url_to_imagegroup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagegroup",
            name="source_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
