# Generated by Django 6.0.3 on 2026-05-03 16:36

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("media_library", "0014_convert_manual_source_type_to_imported"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="media_type",
            field=core.fields.TruncatingCharField(
                choices=[("image", "Image"), ("video", "Video")],
                default="image",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="source_type",
            field=core.fields.TruncatingCharField(
                choices=[
                    ("generated", "AI Generated"),
                    ("imported", "Imported"),
                    ("uploaded", "Uploaded"),
                ],
                default="uploaded",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="mediagroup",
            name="title",
            field=core.fields.TruncatingCharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="mediagroup",
            name="type",
            field=core.fields.TruncatingCharField(
                choices=[
                    ("product", "Product"),
                    ("manual", "Manual"),
                    ("generated", "Generated"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
    ]
