# Generated by Django 6.0.3 on 2026-05-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "media_library",
            "0015_alter_media_media_type_alter_media_source_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="external_url",
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
