# Generated by Django 6.0.3 on 2026-05-05 07:08

import media_library.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_library", "0017_alter_mediagroup_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to=media_library.models.media_upload_to
            ),
        ),
    ]
