# Generated by Django 6.0.3 on 2026-05-03 16:36

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("credits", "0002_remove_creditspend_grant_creditallocation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditgrant",
            name="source",
            field=core.fields.TruncatingCharField(
                choices=[
                    ("signup", "Signup"),
                    ("subscription", "Subscription"),
                    ("manual", "Manual"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="creditgrant",
            name="stripe_invoice_id",
            field=core.fields.TruncatingCharField(
                blank=True, db_index=True, default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="creditspend",
            name="description",
            field=core.fields.TruncatingCharField(max_length=255),
        ),
    ]
