name: Deploy stryng
run-name: ${{ github.event_name == 'workflow_dispatch' && format('[{1}] - {0}', github.workflow, github.event.inputs.environment) || format('[uat] - {0}', github.event.head_commit.message)  }}

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: choice
        options:
        - uat
        - prod
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-stryng-${{ github.event_name }}

    container:
      image: modul8it/stryng_devops_devcontainer:latest
      options: --user 0:0
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    env:
      HOME: /home/coder
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Prepare env (inside container)
        shell: bash
        run: |
          set -euo pipefail
          if [[ "$GITHUB_EVENT_NAME" = "workflow_dispatch" ]]; then
            TARGET_ENV="${{ github.event.inputs.environment }}"
          else
            TARGET_ENV="uat"
          fi
          echo "TARGET_ENV=$TARGET_ENV" >> "$GITHUB_ENV"
          echo "TARGET_ENV_UPPERCASE=${TARGET_ENV^^}" >> "$GITHUB_ENV"
          echo "TARGET_ENV=$TARGET_ENV"
          echo "TARGET_ENV_UPPERCASE=${TARGET_ENV^^}"

      - name: Checkout devops
        uses: actions/checkout@v4
        with:
          repository: modul8dev/devops
          token: ${{ secrets.GH_TOKEN }}
          path: devops
          ref: main

      - name: Deploy (inside container)
        shell: bash
        run: |
          set -eux
          whoami
          echo "TARGET_ENV=$TARGET_ENV"
          echo "TARGET_ENV_UPPERCASE=$TARGET_ENV_UPPERCASE"

          mkdir -p "$HOME/.ssh"
          echo "${{ secrets[format('SSH_PRIVATE_KEY_{0}', env.TARGET_ENV_UPPERCASE)] }}" > "$HOME/.ssh/m8_admin"
          chmod 600 "$HOME/.ssh/m8_admin"

          cd devops/ansible
          ansible-playbook \
            -i "inventories/aws/$TARGET_ENV" \
            -u ubuntu \
            --private-key "$HOME/.ssh/m8_admin" \
            --tags install \
            deploy-stryng5.yml \
            -e "git_ref=${{ github.ref_name }}"
